#ifndef GS1COMMANDS_H
#define GS1COMMANDS_H

#include <common.h>

///////////////////////////////////////////////////////////////////////////////
namespace preagonal::gs1
{
///////////////////////////////////////////////////////////////////////////////

constexpr std::array<std::string_view, 199> serverSideCommands =
{
	"addstring",
	//"addtiledef",
	//"addtiledef2",
	"attachplayertoobj",
	"blockagain",
	//"blockagainlocal",
	"callnpc",
	//"callweapon",
	//"canbecarried",
	//"canbepulled",
	//"canbepushed",
	//"cannotbecarried",
	//"cannotbepulled",
	//"cannotbepushed",
	"canwarp",
	"canwarp2",
	"cannotwarp",
	//"carryobject",
	//"changeimgcolors",
	//"changeimgmode",
	//"changeimgpart",
	//"changeimgvis",
	//"changeimgzoom",
	"deletestring",
	"destroy",
	"detachplayer",
	//"disabledefmovement",
	//"disablemap",
	//"disablepause",
	"disableselectweapons",		// ??
	"disableweapons",			// PLSTATUS_ALLOWWEAPONS?
	"dontblock",
	//"dontblocklocal",
	//"drawaslight",
	"drawoverplayer",
	"drawunderplayer",
	//"enabledefmovement",
	//"enablefeatures",
	//"enablemap",
	//"enablepause",
	"enableselectweapons",
	"enableweapons",
	"explodebomb",				// ?? Could maybe work
	//"followplayer",
	//"freezeplayer",
	"freezeplayer2",
	"hide",
	//"hideimg",
	//"hideimgs",
	//"hidelocal",
	"hideplayer",
	"hidesword",
	"hitcompu",
	"hitnpc",
	"hitobjects",
	"hitplayer",
	"hurt ",
	"insertstring",
	"join ",
	"lay ",
	"lay2",
	//"loadmap",
	"message",
	"move",
	//"noplayerkilling",
	"noplayeronwall",
	//"openurl",
	//"openurl2",
	//"play ",
	//"play2",
	//"playlooped",
	"putbomb",
	"putcomp",
	"putexplosion",
	"putexplosion2",
	"puthorse",
	//"putleaps",				// ??
	"putnewcomp",
	"putnpc",
	"putnpc2",
	"putobject",
	//"reflectarrow",
	//"removearrow",
	"removebomb",
	"removecompus",
	"removeexplo",
	"removehorse",
	"removeitem",
	"removestring",
	//"removetiledefs",
	//"replaceani",
	"replacestring",
	//"resetfocus",
	//"say ",					// ?? - extension possible
	"say2",
	"set ",
	"setani",
	"setarray",
	//"setbackpal",
	"setbeltcolor",
	"setbody",
	"setcharani",
	"setchargender",
	"setcharprop",
	"setcoatcolor",
	//"setcoloreffect",
	//"setcursor ",
	//"seteffect",
	"seteffectmode ",
	//"setfocus",
	"setgender",
	"setgif ",
	"sethead",
	"setimg",
	"setimgpart",
	//"setletters",
	"setlevel ",
	"setlevel2",
	"setmap",
	"setminimap",
	//"setmusicvolume",
	"setplayerdir",
	"setplayerprop",
	"setshape",
	"setshape2",
	"setshield",
	"setshoecolor",
	"setshootparams",
	"setskincolor",
	"setsleevecolor",
	"setstring",
	"setsword",
	//"seturllevel",
	//"setzoomeffect",
	"shoot",
	"shootarrow",
	"shootball",
	"shootfireball",
	"shootfireblast",
	"shootnuke",
	"show",
	"showani",
	"showani2",
	"showcharacter",
	"showfile",
	//"showimg",				// Space?
	//"showimg2",
	//"showlocal",
	//"showpoly",				// Space?
	//"showpoly2",
	"showstats",				// ??
	//"showtext",				// Space?
	//"showtext2",
	"sleep",
	"spyfire",
	//"stopmidi",
	//"stopsound",
	"take ",
	"take2",
	"takehorse",
	"takeplayercarry",
	"takeplayerhorse",
	"throwcarry",
	//"timereverywhere",
	"timershow",
	//"toinventory",
	"tokenize",
	"tokenize2",
	//"toweapons",
	"triggeraction",
	"unfreezeplayer",
	"unset ",
	"updateboard ",
	"updateterrain",
	//"wraptext",
	//"wraptext2",
	"addweapon",
	"removeweapon",
	//"setspritesimage",
	//"setstatusimage",
	"addguildmember",
	"removeguildmember",
	"removeguild",
	"copystrings",
	"copyflagss",				// ?? - Are the double s' intentional?
	"sendtorc",
	"sendtonc",
	"sendpm",
	"setpm",
	"sendrpgmessage",
	"serverwarp",
	"updateboard2 ",
	"setz",
	"setcursor2"
	"copylevel",
	"deletelevel",
	"saveinfo",
	"savelog ",
	"savelog2",
};

///////////////////////////////////////////////////////////////////////////////
}
#endif // GS1COMMANDS_H
