#ifndef GS1COMMANDS_H
#define GS1COMMANDS_H

#include <common.h>
#include <scripting/gs1/ScriptEngineGS1.h>

namespace preagonal::grammar::gs1
{
class GS1Visitor;
}

///////////////////////////////////////////////////////////////////////////////
namespace preagonal::gs1
{
///////////////////////////////////////////////////////////////////////////////

constexpr std::array<std::string_view, 199> serverSideCommands =
{
	"addguildmember",
	"addstring",
	//"addtiledef",
	//"addtiledef2",
	"addweapon",
	"attachplayertoobj",
	"blockagain",
	//"blockagainlocal",
	//"callnpc",
	//"callweapon",
	"canbecarried",
	"canbepulled",
	"canbepushed",
	"cannotbecarried",
	"cannotbepulled",
	"cannotbepushed",
	"cannotwarp",
	"canwarp",
	"canwarp2",
	"carryobject",
	//"changeimgcolors",
	//"changeimgmode",
	//"changeimgpart",
	//"changeimgvis",
	//"changeimgzoom",
	"copyflagss",
	"copylevel",
	"copystrings",
	"deletelevel",
	"deletestring",
	"destroy",
	"detachplayer",
	"disabledefmovement",
	//"disablemap",
	//"disablepause",
	//"disableselectweapons",
	"disableweapons",
	"dontblock",
	//"dontblocklocal",
	"drawaslight",
	"drawoverplayer",
	"drawunderplayer",
	"enabledefmovement",
	//"enablefeatures",
	//"enablemap",
	//"enablepause",
	//"enableselectweapons",
	"enableweapons",
	"explodebomb",
	//"followplayer",
	//"freezeplayer",
	"freezeplayer2",
	"hide",
	//"hideimg",
	//"hideimgs",
	//"hidelocal",
	//"hideplayer",
	//"hidesword",
	"hitcompu",
	"hitnpc",
	"hitobjects",
	"hitplayer",
	"hurt ",
	"insertstring",
	"join ",
	"lay ",
	"lay2",
	//"loadmap",
	"message",
	"move",
	//"noplayerkilling",
	"noplayeronwall",
	//"openurl",
	//"openurl2",
	//"play ",
	//"play2",
	//"playlooped",
	"putbomb",
	"putcomp",
	"putexplosion ",
	"putexplosion2",
	"puthorse",
	//"putleaps",
	"putnewcomp",
	"putnpc",
	"putnpc2",
	//"putobject",
	//"reflectarrow",
	"removearrow",
	"removebomb",
	"removecompus",
	"removeexplo",
	"removeguild",
	"removeguildmember",
	"removehorse",
	"removeitem",
	"removestring",
	//"removetiledefs",
	"removeweapon",
	//"replaceani",
	"replacestring",
	//"resetfocus",
	"saveinfo",
	"savelog ",
	"savelog2",
	//"say ",
	"say2",
	"sendpm",
	"sendrpgmessage",
	"sendtonc",
	"sendtorc",
	"serverwarp",
	"set ",
	"setani",
	"setarray",
	//"setbackpal",
	"setbeltcolor",
	"setbody",
	"setcharani",
	"setchargender",
	"setcharprop",
	"setcoatcolor",
	//"setcoloreffect",
	//"setcursor ",
	//"setcursor2",
	//"seteffect",
	//"seteffectmode ",
	//"setfocus",
	"setgender",
	"setgif ",
	"sethead",
	"setimg",
	"setimgpart",
	//"setletters",
	"setlevel ",
	"setlevel2",
	"setmap",
	"setminimap",
	//"setmusicvolume",
	"setplayerdir",
	"setplayerprop",
	"setpm",
	"setshape",
	"setshape2",
	"setshield",
	"setshoecolor",
	"setshootparams",
	"setskincolor",
	"setsleevecolor",
	//"setspritesimage",
	//"setstatusimage",
	"setstring",
	"setsword",
	//"seturllevel",
	"setz",
	//"setzoomeffect",
	"shoot",
	"shootarrow",
	"shootball",
	"shootfireball",
	"shootfireblast",
	"shootnuke",
	"show",
	"showani",
	"showani2",
	"showcharacter",
	//"showfile",
	"showimg",
	"showimg2",
	//"showlocal",
	//"showpoly",
	//"showpoly2",
	"showstats",
	//"showtext",
	//"showtext2",
	"sleep",
	"spyfire",
	//"stopmidi",
	//"stopsound",
	"take ",
	"take2",
	"takehorse",
	"takeplayercarry",
	"takeplayerhorse",
	"throwcarry",
	//"timereverywhere",
	"timershow",
	//"toinventory",
	"tokenize",
	"tokenize2",
	//"toweapons",
	"triggeraction",
	"unfreezeplayer",
	"unset ",
	"updateboard ",
	"updateboard2 ",
	"updateterrain",
	//"wraptext",
	//"wraptext2",
};

/*
	triggeractions:
		serverside		- when received from client, triggers the weapon script of the weapon listed in first parameter.
		server{EVENT}	- invokes an event on the control-npc: if (actionserver{EVENT})
*/

void processBuiltInCommand(preagonal::grammar::gs1::GS1Visitor* visitor, antlr4::tree::ParseTree* node, std::string_view commandName);

///////////////////////////////////////////////////////////////////////////////
}
#endif // GS1COMMANDS_H
